server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    username: root
    password: 12345678
  application:
    name: user-service
mybatis:
  type-aliases-package: cn.itcast.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka